language: node_js
addons:
  chrome: stable
cache: npm
sudo: false
node_js:
  - '10'

matrix:
  fast_finish: true

before_script:
  - npm ci
  - npm install coveralls

script:
  - npm run tslint
  - npm test
  - npm run coveralls
