language: node_js

cache: yarn

sudo: false

node_js:
  - '8'

matrix:
  fast_finish: true

before_install:
  - export CHROME_BIN=chromium-browser

before_script:
  - npm prune
  - export DISPLAY=:99.0
  - npm install coveralls

script:
  - npm run tslint
  - npm test
  - npm run coveralls
